### ISSUE TITLE
How to Check the Correctness of CKKS Encrypted Array?  

### ISSUE THREAD

**Issue by ShokofehVS** [ShokofehVS/SecBic-CCA#7]
**Description**

First 2D input matrix should be flattened into a 1D vector. Afterwards, ciphertexts hold all the elements at once, so that all operations are applied to all values at once. The question is that how we can check the correctness of resulting ciphertexts.

**Code To Reproduce Question**

```
import numpy as np
from Pyfhel import Pyfhel, PyCtxt

# HE SETUP
HE = Pyfhel(context_params={'scheme': 'CKKS', 'n': 2 ** 14,
                            'scale': 2 ** 30, 'qi_sizes': [60, 30, 30, 30, 60]},
            key_gen=True)
HE.rotateKeyGen()     # We will use it to rotate the values in the vector

# DATA GENERATION
n_rows, n_cols = 10, 5
n_elements = n_rows*n_cols
np.random.seed(42)                                    # Fixed seed for reproducibility
data = np.random.randint(0, 5, size=(n_rows, n_cols)) # Generate data

# Encryption -> Flatten to 1D vector of size (n_rows x n_cols) and encrypt as-is
flattened_data = data.flatten()                       
enc_data = HE.encryptFrac(flattened_data.astype(np.float64))

# Row-wise sum
enc_rowwise_sum = PyCtxt(copy_ctxt=enc_data)
for i in range(1,n_cols):
    enc_rowwise_sum += enc_data << i

# Row-wise mean
enc_row_means = enc_rowwise_sum / len(cols)
```

**Comment by ibarrond** [comment]
If testing locally, you can decrypt (e.g., `HE.decrypt(enc_row_means)`) and compare the obtained result with the expected one with `np.allclose`. Doing this many times with randomized inputs of a given shape mimicking the real inputs can help empirically determine the amount of error introduced by using CKKS to compute the operations.

Checking correctness online is a much more complex process, since you need to protect against malicious adversaries arbitrarily modifying the computation and/or its result. This goes far beyond the current capabilities of the existing popular HE libraries.
